MxOnline/urls.py
# _*_ coding:utf-8 _*_
"""MxOnline URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
import  xadmin
from django.views.static import serve


from users.views import IndexView, LoginView, RegisterView, LogoutView, ActiveUserView
from MxOnline.settings import MEDIA_ROOT

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name='user_active'),

    #配置验证码
    url(r'^captcha/', include('captcha.urls')),

    #配置上传文件的访问处理函数
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),

    #配置静态文件的访问处理函数
    # url(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),

    #视频作品url配置
    url(r'^movie/', include('movies.urls', namespace='movie')),

    #本子url配置
    url(r'^book/', include('book.urls', namespace='book')),

    #音乐url配置
    url(r'^music/', include('music.urls', namespace='music')),
    #资源url配置
    url(r'^resource/', include('resource.urls', namespace='resource')),

    #用户中心url配置
    url(r'^user/', include('users.urls', namespace='user')),

    #文章url配置
    url(r'^article/', include('article.urls', namespace='article')),

    #富文本相关
    url(r'^ueditor/', include('DjangoUeditor.urls')),

]

#全局404页面配置
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

apps/book/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'xiaohai'
__date__ = '2017/3/31 14:17'

from django.conf.urls import url, include

from .views import BookListView, BookDetailView, BookAddView
from .upload import upload_image

urlpatterns = [
    #本子列表页
    url(r'^list/$', BookListView.as_view(), name='book_list'),
    #本子详情页
    url(r'^detail/(?P<book_id>\d+)/$', BookDetailView.as_view(), name='book_detail'),
    #本子添加页
    url(r'^add/$', BookAddView.as_view(), name='book_add'),
    #本子编辑器图片上传
    url(r'^upload/(?P<dir_name>[^/]+)$', upload_image, name='upload_image'),
]

apps/movie/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'xiaohai'
__date__ = '2017/3/31 14:17'

from django.conf.urls import url, include

from .views import MovieListView, MovieDetailView


urlpatterns = [
    #课程列表页
    url(r'^list/$', MovieListView.as_view(), name='movie_list'),
    url(r'^detail/$', MovieDetailView.as_view(), name='movie_detail'),

]

apps/music/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'xiaohai'
__date__ = '2017/3/31 14:17'

from django.conf.urls import url, include
from .views import MusicListView, MusicDetailView, MusicAddView


urlpatterns = [
    #音乐列表页
    url(r'^list/$', MusicListView.as_view(), name='music_list'),
    # 音乐详情页
    url(r'^detail/(?P<music_id>\d+)/$', MusicDetailView.as_view(), name='music_detail'),
    # 音乐添加液
    url(r'^add/$', MusicAddView.as_view(), name='music_add'),
]

apps/users/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'xiaohai'
__date__ = '2017/3/31 14:17'

from django.conf.urls import url, include

from .views import UserCenterListView, AddCommitsView, UserCenterMovieView, \
                    UserCenterArticleView, UserCenterBookView, AddFavView, UserCenterCollectView, UserCenterMusiceView, \
                    UserCenterResourceView


urlpatterns = [
    #用户中心页
    url(r'^info/(?P<user_id>\d+)/$', UserCenterListView.as_view(), name='user_info'),
    #用户中心视频页
    url(r'^info/movie/(?P<user_id>\d+)/$', UserCenterMovieView.as_view(), name='user_movie'),

    #用户中心文章页
    url(r'^info/article/(?P<user_id>\d+)/$', UserCenterArticleView.as_view(), name='user_article'),

    #用户中心本子页
    url(r'^info/book/(?P<user_id>\d+)/$', UserCenterBookView.as_view(), name='user_book'),
    #用户中心音乐页
    url(r'^info/music/(?P<user_id>\d+)/$', UserCenterMusiceView.as_view(), name='user_music'),
    #用户中心资源页
    url(r'^info/resource/(?P<user_id>\d+)/$', UserCenterResourceView.as_view(), name='user_resource'),
    #用户中心收藏页
    url(r'^info/collect/(?P<user_id>\d+)/$', UserCenterCollectView.as_view(), name='user_collect'),

    #添加评论也
    url(r'^add_commit/$', AddCommitsView.as_view(), name='add_commit'),
    #添加收藏
    url(r'^add_fav/$', AddFavView.as_view(), name='add_fav'),


    #图片上传
    url(r'^upload_image/$', UserCenterListView.as_view(), name='upload_image'),
]

extra_apps/xadmin/views/base.py
import sys
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.utils.encoding import force_unicode, force_text
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_unicode, smart_unicode, smart_str
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, basestring) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_unicode(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        for r in remove:
            for k in p.keys():
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        for r in remove:
            for k in p.keys():
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

    def init_request(self, *args, **kwargs):
        pass

    def init_plugin(self, *args, **kwargs):
        plugins = []
        for p in self.base_plugins:
            p.request = self.request

templates/articleadd.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}FD动漫爱好网-本子添加{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bookadd.css' %}">
{% endblock %}

{% block content %}
    <form id="jsAvatarForm" action="{% url 'article:article_add' %}" enctype="multipart/form-data" method="post">

        <select name="tag">
            <option value="jl">交流</option>
            <option value="dhzx">动画资讯</option>
            <option value="qtzx">其他资讯</option>
            <option value="fdsw">fd事务</option>
        </select>

        <input type="file" name="image" id="avatarUp" class="js-img-up"/>

        名字：<input type="text" name="name" />

        描述<input type="text" name="desc" />

        <textarea id="editor_id" name="detail"></textarea>
        {% csrf_token %}
        <input type="submit">
    </form>

    <button onclick="xiaohai()">ss</button>
{% endblock %}



{% block js %}
    <script src="{% static 'js/kindeditor/kindeditor-all-min.js' %}"></script>
    <script src="{% static 'js/kindeditor/lang/zh-CN.js' %}"></script>

<script>
    /**
 * Created by Administrator on 2017/4/14.
 */

function xiaohai() {
        console.log($('#editor_id').val())
    }
KindEditor.ready(function(K){
    K.create('#editor_id',{
        width:500,
        height:200,
        uploadJson: '/book/upload/kindeditor',
        afterBlur: function(){this.sync();}
    })
})
</script>


{% endblock %}

templates/usercenter-base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>{% block title %}FD动漫爱好网{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/user.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/Semantic-UI-CSS-master/semantic.css' %}">
    {% block css %}{% endblock %}
</head>
<body>

<div class="header-wrapper">
        <div class="header-content">
            <div class="middle">
                <div class="info">
                    <a href="{% url 'index' %}"><div class="item"><span class="icon icon-tv"></span>主页</div></a>
                    <div class="item">画友</div>
                    <div class="item">游戏中心</div>
                    <div class="item">直播</div>
                    <div class="item">周边</div>
                    <div class="item">萌战</div>
                </div>
                {% if request.user.is_authenticated %}
                <div class="user">
                    <a href="{% url 'user:user_info' request.user.id %}"><div class="item">用户</div></a>
                    <div class="item">消息</div>
                    <div class="item">动态</div>
                    <div class="item">收藏夹</div>
                    <div class="item">历史</div>
                    <div class="item">投稿</div>
                    <a href="{% url 'logout' %}"><div class="item">退出</div></a>
                </div>
                {% else %}
                <div class="user">
                    <a href="{% url 'login' %}"><div class="item">登录</div></a>
                    <a href="{% url 'register' %}"><div class="item">注册</div></a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
<div class="user-page">
  <div class="xiaohai-container">
    <div class="user-banner"></div>

    <div class="user-nav" >
      <img src="{{ MEDIA_URL }}{{ user_info.image }}"  alt="" width="100" height="100" style="margin-top: -50px;border-radius: 50%" >

        <a href="{% url 'user:user_info' user_info.id %}">
      <div class="user-nav-item {% ifequal category 'home' %}active{% endifequal %}">
        <div style="color: #55bd94" class="fa fa-home "></div>
        <div>主页</div>
      </div></a>

    <a href="{% url 'user:user_movie' user_info.id %}">
      <div  class="user-nav-item  {% ifequal category 'movie' %}active{% endifequal %}" >
        <div style="color: #4bb4d6" class="fa fa-youtube-play"></div>
        <div >视频</div>
      </div></a>


        <a href="{% url 'user:user_article' user_info.id %}">
      <div class="user-nav-item {% ifequal category 'article' %}active{% endifequal %}">
        <div style="color: #f25d8e" class="fa fa-coffee"></div>
        <div>茶会</div>
      </div></a>

        <a href="{% url 'user:user_book' user_info.id %}">
      <div class="user-nav-item {% ifequal category 'book' %}active{% endifequal %}">
        <div style="color: #5fc7e9" class="fa fa-leanpub"></div>
        <div>本子</div>
      </div></a>

    <a href="{% url 'user:user_music' user_info.id %}">
      <div class="user-nav-item {% ifequal category 'music' %}active{% endifequal %}">
        <div style="color: #F18E39" class="fa fa-music"></div>
        <div>音乐</div>
      </div></a>

    <a href="{% url 'user:user_resource' user_info.id %}">
      <div class="user-nav-item {% ifequal category 'resource' %}active{% endifequal %}">
        <div style="color: #B45FE9" class="fa fa-file-text"></div>
        <div>资源</div>
      </div></a>

    {% if user_info.id == request.user.id %}
    <a href="{% url 'user:user_collect' user_info.id %}">
      <div class="user-nav-item {% ifequal category 'collect' %}active{% endifequal %}" >
        <div style="color: #f86952" class="fa fa-star-half-empty"></div>
        <div>收藏</div>
      </div></a>
    {% endif %}

      <div class="user-nav-item" >
        <div style="color: #e8a44c" class="glyphicon glyphicon-star"></div>
        <div>订阅</div>
      </div>

{#      <div class="user-nav-item-active"></div>#}
    </div>

    <div class="user-box" >

      <div class="user-box-left" >
        {% block content %}


        {% endblock %}
      </div>



      <div class="user-box-right" >
          {% if request.user.id == user_info.id %}
        <div class="user-upload" >
          <div class="create-center" >
            <img src="{% static 'images/upload_icon.png' %}" alt="" height="70" width="70">
            <span style="margin-left: 10px;">创作中心</span>
          </div>
          <div class="upload-box" >
              <a href="{% url 'movie:movie_add' %}"><div>
              <span class="fa fa-cloud-upload"></span>
              <span>: 上传视频</span>
            </div></a>
            <div class="middle-border" ></div>
            <div>
              <span class="fa fa-cogs"></span>
              <span>视频管理</span>
            </div>
          </div>
        </div>

        <div class="user-upload" >
          <div class="create-center" >
            <img src="{% static 'images/upload_icon.png' %}" alt="" height="70" width="70">
            <span style="margin-left: 10px;">创作中心</span>
          </div>
          <div class="upload-box" >
              <a href="{% url 'music:music_add' %}"><div>
              <span class="fa fa-cloud-upload"></span>
              <span>: 上传音乐</span>
            </div></a>
            <div class="middle-border" ></div>
            <div>
              <span class="fa fa-cogs"></span>
              <span>视频管理</span>
            </div>
          </div>
        </div>

          <div class="user-upload" >
          <div class="create-center" >
            <img src="{% static 'images/upload_icon4.png' %}" alt="" height="70" width="70">
            <span style="margin-left: 10px;">创作中心</span>
          </div>
          <div class="upload-box" >
              <a href="{% url 'book:book_add' %}"><div>
              <span class="fa fa-cloud-upload"></span>
              <span>: 上传本子</span>
            </div></a>
            <div class="middle-border" ></div>
            <div>
              <span class="fa fa-cogs"></span>
              <span>视频管理</span>
            </div>
          </div>
        </div>


        <div class="user-upload" >
          <div class="create-center" >
            <img src="{% static 'images/upload_icon5.png' %}" alt="" height="70" width="70">
            <span style="margin-left: 10px;">创作中心</span>
          </div>
          <div class="upload-box" >
              <a href="{% url 'article:article_add' %}"><div>
              <span class="fa fa-cloud-upload"></span>
              <span>: 上传文章</span>
            </div></a>
            <div class="middle-border" ></div>
            <div>
              <span class="fa fa-cogs"></span>
              <span>视频管理</span>
            </div>
          </div>
        </div>
              <div class="user-upload" >
          <div class="create-center" >
            <img src="{% static 'images/upload_icon5.png' %}" alt="" height="70" width="70">
            <span style="margin-left: 10px;">创作中心</span>
          </div>
          <div class="upload-box" >
              <a href="{% url 'resource:resource_add' %}"><div>
              <span class="fa fa-cloud-upload"></span>
              <span>: 上传资源</span>
            </div></a>
            <div class="middle-border" ></div>
            <div>
              <span class="fa fa-cogs"></span>
              <span>视频管理</span>
            </div>
          </div>
        </div>
            {% endif %}

        <div class="use-notice" >
          <h3 >公告</h3>
          <div class="hr" style="margin-top: 5px;"></div>
          <div class="user-desc" >
            asdsajkdhskjadksanjbskjdskjankjasdasdasdashndkashkdhsakhdsahkdska
          </div>
        </div>

        <div class="user-care" >

          <div class="user-care-item" >
            <div>
              <span style="margin-right: 3px;">关注</span>
              <span >68</span>
            </div>
            <div class="border-top" ></div>
            <div>
              <span style="margin-right: 3px;">粉丝</span>
              <span>68</span>
            </div>

          </div>




        </div>
      </div>

    </div>
  </div>
</div>
</body>
</html>

templates/usercenter-collect.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}

{% block title %}FD动漫爱好网-本子列表{% endblock %}

{% block content %}

        <div class="hr"></div>


        <div class="user-category-wrapper clearfix">
            <div class="user-title" >
            <div class="user-title-box" >
              <div class="desc" >收藏本子</div>
              <div class="badge" ></div>
              <div class="news" >最新发布</div>
              <div class="see" >最多播放</div>
            </div>


            <div class="more" >
                <a href="{% url 'user:user_movie' user_info.id %}">更多 ></a>
            </div>

          </div>



            {% for book in book_user %}
            <div  class="user-video-box" >
              <a href="{% url 'book:book_detail' book.id %}"><img src="{{ MEDIA_URL }}{{ book.image }}" alt="" width="100%" height="100px"></a>
              <p class="desc">{{ book.desc }}</p>
              <div class="see-box" >
                <div class="see-item" >
                  <span>播放:</span>
                  <span >{{ book.click_nums }}</span>
                </div>

                <div class="see-item" >
                  <span>收藏:</span>
                  <span>{{ book.fav_nums }}</span>
                </div>

              </div>
            </div>
            {% endfor %}
        </div>


      <div class="hr"></div>


            <div class="user-category-wrapper clearfix">
            <div class="user-title" >
            <div class="user-title-box" >
              <div class="desc" >收藏视频</div>
              <div class="badge" ></div>
              <div class="news" >最新发布</div>
              <div class="see" >最多播放</div>
            </div>

            <div class="more" >
            更多 >
            </div>

          </div>



            {% for movie in movie_user %}
            <div  class="user-video-box" >
              <a href="{% url 'movie:movie_detail' movie.id %}"><img src="{{ MEDIA_URL }}{{ movie.image }}" alt="" width="100%" height="100px"></a>
              <p class="desc">{{ movie.desc }}</p>
              <div class="see-box" >
                <div class="see-item" >
                  <span>播放:</span>
                  <span >{{ movie.click_nums }}</span>
                </div>

                <div class="see-item" >
                  <span>收藏:</span>
                  <span>{{ movie.fav_nums }}</span>
                </div>

              </div>
            </div>
            {% endfor %}
        </div>


      <div class="hr"></div>

            <div class="user-category-wrapper clearfix">
            <div class="user-title" >
            <div class="user-title-box" >
              <div class="desc" >收藏文章</div>
              <div class="badge" ></div>
              <div class="news" >最新发布</div>
              <div class="see" >最多播放</div>
            </div>

            <div class="more" >
            更多 >
            </div>

          </div>



            {% for article in article_user %}
            <div  class="user-video-box" >
              <a href="{% url 'article:article_detail' article.id %}"><img src="{{ MEDIA_URL }}{{ article.image }}" alt="" width="100%" height="100px"></a>
              <p class="desc">{{ article.desc }}</p>
              <div class="see-box" >
                <div class="see-item" >
                  <span>播放:</span>
                  <span >{{ article.click_nums }}</span>
                </div>

                <div class="see-item" >
                  <span>收藏:</span>
                  <span>{{ article.fav_nums }}</span>
                </div>

              </div>
            </div>
            {% endfor %}
        </div>


      <div class="hr"></div>
    
        <div class="user-category-wrapper clearfix">
            <div class="user-title" >
            <div class="user-title-box" >
              <div class="desc" >收藏音乐</div>
              <div class="badge" ></div>
              <div class="news" >最新发布</div>
              <div class="see" >最多播放</div>
            </div>

            <div class="more" >
            更多 >
            </div>

          </div>



            {% for music in music_user %}
            <div  class="user-video-box" >
              <a href="{% url 'music:music_detail' music.id %}"><img src="{{ MEDIA_URL }}{{ music.image }}" alt="" width="100%" height="100px"></a>
              <p class="desc">{{ music.desc }}</p>
              <div class="see-box" >
                <div class="see-item" >
                  <span>播放:</span>
                  <span >{{ music.click_nums }}</span>
                </div>

                <div class="see-item" >
                  <span>收藏:</span>
                  <span>{{ music.fav_nums }}</span>
                </div>

              </div>
            </div>
            {% endfor %}
        </div>

        <div class="hr"></div>

        <div class="user-category-wrapper clearfix">
            <div class="user-title" >
            <div class="user-title-box" >
              <div class="desc" >收藏资源</div>
              <div class="badge" ></div>
              <div class="news" >最新发布</div>
              <div class="see" >最多播放</div>
            </div>

            <div class="more" >
            更多 >
            </div>

          </div>



            {% for resource in resource_user %}
            <div  class="user-video-box" >
              <a href="{% url 'resource:resource_detail' resource.id %}"><img src="{{ MEDIA_URL }}{{ resource.image }}" alt="" width="100%" height="100px"></a>
              <p class="desc">{{ resource.desc }}</p>
              <div class="see-box" >
                <div class="see-item" >
                  <span>播放:</span>
                  <span >{{ resource.click_nums }}</span>
                </div>

                <div class="see-item" >
                  <span>收藏:</span>
                  <span>{{ resource.fav_nums }}</span>
                </div>

              </div>
            </div>
            {% endfor %}
        </div>

{% endblock %}